### ISSUE TITLE
8.4.7 Crash when estimating NRTL IP[Bug] 

### ISSUE THREAD

**Issue by jkittrell** [DanWBR/dwsim6#495] opened 2023-06-22 17:31 UTC
**Describe the bug**
After upgrading from 8.4.6 to 8.4.7 DWSIM crashes when selecting a material stream or initiating simulation on existing flowsheet.  May be related to prior issue #458, I believe was attributed to estimation of NRTL IP.  In 8.4.6, simulation successfully solves, I see message in Log Panel "Estimated NRTL IP set for furfural/tetrahydrofuran".  I'm not getting an error report on this one, just shutsdown, but same flowsheet under 8.4.7 crashes before that message appears making me think it might be related or has resurfaced?

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version 11.7.6

**Additional context**
Symptoms similar to issue #458

**Comment by DanWBR** [comment] 2023-06-22 17:55
@jkittrell did you try it in v8.5.0?

**Comment by jkittrell** [comment] 2023-06-22 18:09
Yes, same symptoms unfortunately

**Comment by DanWBR** [comment] 2023-06-22 18:12
@jkittrell do you have a flowsheet that I could use?

**Comment by jkittrell** [comment] 2023-06-22 18:15
sure, use this one
[iCARD_THF_recycle.dwxmz.zip](https://github.com/DanWBR/dwsim/files/11837908/iCARD_THF_recycle.dwxmz.zip)

**Comment by DanWBR** [comment] 2023-06-24 15:59
@jkittrell it didn't crash for me, got this instead:

`[6/24/2023 11:58:45 AM] Estimated NRTL IP set for Furfural/Tetrahydrofuran: -162.51/741.22/0.2`

**Comment by DanWBR** [comment] 2023-06-24 16:02
@jkittrell the above was with v8.5.0. If it is still crashing for you, try to run it from the console and get some meaninful error message that could help us to track the issue.

**Comment by jkittrell** [comment] 2023-06-24 17:56
certainly
2023-06-24 12:39:44.015 Launcher.exec[61957:11322211] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'NSWindow drag regions should only be invalidated on the Main Thread!'
[Terminal Saved Output.pdf](https://github.com/DanWBR/dwsim/files/11857848/Terminal.Saved.Output.pdf)

**Comment by DanWBR** [comment] 2023-06-24 18:30
@jkittrell can you attach the errors.log and lasterror.txt files from DWSIM Application Data folder, please?

**Comment by DanWBR** [comment] 2023-07-10 14:07
closing this due to being unable to reproduce and lack of additional data.

**Closed as completed by DanWBR** 2023-07-10 14:07 UTC
Labels: bug, needs info, unable to reproduce
