### ISSUE TITLE
[Bug] wrong Cv calculation; valve has so many problems

### ISSUE THREAD

**Issue by hsfmailubcca** [DanWBR/dwsim6#672] opened 2024-09-10 17:45 UTC
IMPORTANT: This section is meant for bug reporting only. For usage issues, please go to the [Support Forums](https://sourceforge.net/p/dwsim/discussion/).

**Describe the bug**
Overall, the valve cannot take small to medium values of Cv's and produce wrong pressure drops (verified with AFT Arrrow and Aspen HYSYS).   For example:
Tin=298.15 K, Pin=1,000 bara, Pout=1 bar, flow= 1 kg/s, it gives a Cv of 251.092, which is way far of reality.   The Cv is 1.1 calculated by other software and also Swagelok valve Cv calculator.

**To Reproduce**

PLEASE ATTACH THE ZIPPED FLOWSHEET FILE and/or inform the steps to reproduce the behavior:

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Linux, macOS]
 - Version [e.g. v6.4.1]

**Additional context**

**Comment by DanWBR** [comment] 2024-09-10 18:00
@hsfmailubcca Pin=1,000 bara, Pout=1 bar means critical flow, that the valve model doesn't support. how about the other problems? (you wrote "so many")

**Comment by hsfmailubcca** [comment] 2024-09-10 19:56
Hi Daniel,

Thank you for your response and making the software.  It is really hard to
make a such a comprehensive software.

There are some other.  E.g., when I pick the pressure drop instead of Cv, I
can go down to very small Cv's with no error but when pick the same Cv, ir
does not produce the corresponding pressure drop.

Also some other bugs such as temperature which can be discussed in an
online meeting if necessary.

I am also not sure how good the software can handle choked flows.

Best regards,
Hamidreza Sadeghifar, PhD, P.Eng.

**Comment by hsfmailubcca** [comment] 2024-09-10 21:24
Also, choked flow is included in your user guide and the software can
handle choked flow to some extent.

**Comment by DanWBR** [comment] 2024-09-10 22:05
Maybe @andr1976 can help us here as he is the author of the current Cv code in the valve model, otherwise I'll have to rewrite it from scratch.

**Comment by andr1976** [comment] 2024-09-10 22:59
@hsfmailubcca can you upload a file for us to investigate? Its hard check without

**Comment by hsfmailubcca** [comment] 2024-09-11 01:26
I have got results for critical flow but when the pressure difference
becomes very high, the software pops up a message saying that the valve is
too small.     I think there is a limiting condition for the formula used.
   You can use formula provided in AFT Arrow user guide and just do it as
it without putting any limitation.

Overall, DWSIM is a good software; if you can fix this part, then I can
validate it for you against other software and then here in our company we
can use DWSIM and also provide some donations. DWSIM is a good software and
just needs a little bit of work to extend its application to high pressure
gases and validate them.

**Comment by hsfmailubcca** [comment] 2024-09-11 01:27
Sure. I will. I have it on my laptop and send it to you in a few hours.

**Comment by hsfmailubcca** [comment] 2024-09-11 14:21
Please find the file attached

**Comment by andr1976** [comment] 2024-09-11 18:18
Did you attach the file? I can't see it anywhere

**Comment by hsfmailubcca** [comment] 2024-09-11 18:36
Yes, I did.  Please scroll all the way to the bottom thread.

**Comment by andr1976** [comment] 2024-09-11 18:43
What is the fluid? and the temperature?

**Comment by hsfmailubcca** [comment] 2024-09-11 19:17
H2 gas; temperature can be set at 25 C or 10 C.

I check the same example with HYSYS with no error.   HYSYS still does not
allow very low Cv's but its temperatures are very reasonable.   For
example, Hysys provide a temperature increase from 10 to 38 degrees but
DWSIM from 10 to 1807 K (~1500 C) which is not reasonable.
 Interestingly, AFT Arrow provides the choked warning but still gives the
pressure drop and the pressure of the outlet.     I have attached the DWSIM
of this example that provides an unreasonable outlet T of 1807 K.     I
suggest you use the formulae used in AFT Arrow; you can find via google.

**Comment by andr1976** [comment] 2024-09-11 20:15
@hsfmailubcca 
Please do the following: 

1) zip the simulation file and drop it in a comment field here in a browser (not via mail). The file has not been uploaded
2) Inform DWSIM version used
3) Which mode:  Dynamic or steady-state? 

Assuming steady-state for now
Then some things seems completely off. The heating due to reverse J-T effect is well produced in DWSIM, take e.g. the CoolProp property package which has the fundamental equation of state for hydrogen. Please make sure the same fluid package is applied both upstream, for the valve and downstream, since the enthalpy basis may be different from fluid package to fluid package messing up the temperature calculation for the PH flash. You will get something between 25-60 C depending on the initial temperature. 
Then I would bet your strangely high Cv is due to something like this, When I do the calc in DWSIM from 1000 to 1 bar, I get a Cv of 1.01, in our in-house control valve calculation methods also based on IEC/ANSI/ISA  (as in DWSIM) I get the same result. 

The caveat comes if you supply the Cv and calculate the pressure drop. Since the flow is choked, there is no explicit way of going below the critical pressure, since it has no effect any longer - remember the flow is specified upstream, so is pressure. With the given Cv the required outlet pressure to give you this will be the critical pressure. So although you sized for a dP of 999 bar, this is not what you will get in the reverse calculations due to the critical conditions. 

Hydrogen at 1000 bar is tricky. Not all fluid packages in DWSIM will manage e.g. SRK and GERG in DWSIM. Peng-Robinson will, but I would not trust it for pure hydrogen at 1000 bar. DWSIM has limitations since it does not allow you to calculate flow based on pressure drop, nor doing backwards calculations propagating downstream to upstream (unless using Pro I assume), thus the things you can do with a valve in steady state will be limited to some extent

**Comment by hsfmailubcca** [comment] 2024-09-11 20:59
Here you go.

**Comment by hsfmailubcca** [comment] 2024-09-11 21:00
[ValveCv_1.zip](https://github.com/user-attachments/files/16970400/ValveCv_1.zip)

**Comment by hsfmailubcca** [comment] 2024-09-11 21:02
Steady State; the last (most recent ) version of DWSIM
I just dropped the file; I had sent it via my email and that's why you
could not see it.

**Comment by hsfmailubcca** [comment] 2024-09-11 21:03
I just dropped the file; I had sent it via my email and that's why you
could not see it.

**Comment by andr1976** [comment] 2024-09-11 21:10
The error is here you scale the Cv to 0.4% at full opening. Remove the scaling and all is good 
![image](https://github.com/user-attachments/assets/c9e2cae5-df44-4c17-9523-502ce85f1d70)

**Comment by andr1976** [comment] 2024-09-11 21:11
For Peng-Robinson the compressibility starts being off at 10 C and 1000 bar, at 25 bar t is reasoanable. I would use CoolProp for pure hydrogen at these extreme values

**Comment by hsfmailubcca** [comment] 2024-09-11 21:35
Thanks Anders.    
CoolProp gives much more reasonable temperatures.   
Still it can solve for Cv's above 1.1 for this example.     For Cv's less than 1.1, it cannot solve.   I was able to solve a similar example for any Cv's using AFT Arrow.   I am not saying your results are incorrect but it does not cover any Cv's.

HYSYS also does something similar to DWSIM and only solves for some Cvs if ISA method is selected.     HYSYS can do for lower Cv's if its other methods is elected.   

With CoolProp, DWSIM and HYSYS results are very close and almost the same since both use the ANSI/ISA method.


That 0.4 was not coming to play in my simulation since the section box had not be checked.

**Comment by hsfmailubcca** [comment] 2024-09-11 21:36
With CoolProp, the results are correct; the only issue remains unsolved is that both HYSYS and DWSIM cannot do for low Cv's of valves (if ANSI/ISA method selected in HYSYS) but AFT Arrow can do.     For the file attached, the lowest CV is 1.1  but my valve Cv is 0.8 and i need results for my real application.

**Comment by andr1976** [comment] 2024-09-11 21:41
The problem is the fixed mass flow and the critical conditions, which is
not possible with a lower Cv. Only solution is to lower mass flow
accordingly.

ons. 11. sep. 2024 kl. 23.36 skrev hsfmailubcca ***@***.***>:

**Comment by hsfmailubcca** [comment] 2024-09-11 21:45
Ok, I will double check it against AFT Arrow and see how accurate AFT Arrow is for low Cv's; I will try yo make apples-to-apples comparisons between HYSYS, DWSIM and AFT Arrow for such extreme conditions.

I think you are right Anders; even AFT Arrow cannot do it for low CV's; I do not have access to AFT but in the past, I was doing the reverse; giving all the Cv's and resistances to AFT and AFT was giving me the flow.   The way I see it now is that AFT gives the min available flow that it can solve.

**Comment by andr1976** [comment] 2024-09-12 06:24
@DanWBR I think you can close this one and @hsfmailubcca can still add comments/updates on the AFT results

**Closed as completed** 2024-10-01 19:32 UTC
Labels: bug

**Comment by hsfmailubcca** [comment] 2024-10-03 17:33
Having done two cases, I found DWSIM produces results very similar to HYSYS even though there are still some minor differences.   E.g., DWSIM only has Cv but HYSYS and AFT have Cv and Xt parameters.     
1- Does DWSIM have PSV sizing as well?
2- Does DWSIM have something like an "Adjust" function that we can change one variable to reach a target value for another variable? E.g., I want to change flow to reach a specific/target value for the outlet temperature?
3-  I see that DWSIM also has Dynamic.    How can I model a **transient flow** from a 100-bar tank to a 5-bar tank connected via a valve with a Cv of 1?   I need this transient flow as a function of time.
