### ISSUE TITLE
Pipe thermal profile [Bug] 

### ISSUE THREAD

**Issue by DarshVader23** [DanWBR/dwsim6#654] opened 2024-06-26 16:05 UTC
IMPORTANT: This section is meant for bug reporting only. For usage issues, please go to the [Support Forums](https://sourceforge.net/p/dwsim/discussion/).

A clear and concise description of what the bug is.:
The heat transfer from a 1m pipe carrying water at 75°C varies from 19,643W when no air is blowing over the pipe to 236W when air at 1 m/s is blowing over the pipe.

**To Reproduce**

Setup: A stainless steel  3" pipe sch 40 that is 1m in length with zero elevation.  Water flow through pipe at 75°C at 10 m³/h.
Thermal profile is set to estimate the overall heat transfer coeffiecent with the external temperature set to 10°C.
The "include pipe walls" and "include internal HTC" are selected.
The insulation and external HTC are NOT selected.

The calculated heat transfer over a 1m pipe is 19,643 W, so the tempetature drops from 75 to 73°C.
If you include the External HTC using "Air" with a velovity set to 1 m/s the heat transfer is 235 W.

[Pipe.zip](https://github.com/user-attachments/files/15991875/Pipe.zip)

PLEASE ATTACH THE ZIPPED FLOWSHEET FILE and/or inform the steps to reproduce the behavior:

**Expected behavior**
The heat transfer should be higher when the air is blowing over the pipe.

**Desktop (please complete the following information):**
Windows 11
DWSIM version 8.7.1

**Comment by DanWBR** [comment] 2024-06-27 11:34
@DarshVader23 this is by design. If you do not check the external HTC option, DWSIM will not take it into account as a resistance to heat transfer, hence the high value for heat transferred. If you want to model a real world piping system, you have to use it.

**Closed as completed by DanWBR** 2024-06-27 11:34 UTC
Labels: not a bug
