### ISSUE TITLE
[Bug] CoolProp minimum temperature issues

### ISSUE THREAD

**Issue by PaalRT** [DanWBR/dwsim6#269] opened 2022-01-17 19:02 UTC
Hi,

i'm a new user that just finished your youtube courses, so this issue might be due to my beginner's knowledge. 
If so, i apologize.

My issue is that i'm trying to model a heat exchanger with the CoolProp (Incompressible Mixtures) Property package.
I've used the following:
-Hot Fluid: Water
-Cold Fluid: 50/50 wt% Water / ethylene glycol 

1.  Select Water and Ethylene Glycol
2.  Select CoolProp (Incompressible Mixtures) Property Package
3.  Go to Settings in the "Added Property Packages" Window
4.  Go to Model Parameters
5.  Select Water as DWSim Solvent, Ethylene Glycol as DWSim Solute and MEG (Ethylene Glycol -aq) as CoolProp Solute.
6.  Next, select C5 units and then finish 
7. Insert Heat Exchanger and add four streams
8. Click on hot fluid inlet stream and write temperature = 60C
9. Go to compound amounts and write water 1 and ethylene glycol 0. Then accept.
10. Click on cold fluid inlet stream and write temperature = 35C
11. Go to compound amounts, select mass and write 0.5 water and 0.5 ethylene glycol, then accept.
12. Click on Heat Exchanger and select calculate hot fluid outlet temperature. Wite Cold fluid outlet temperature = 45C
13. Now an error code reads "HE-01: Your temperature 234.953400 is below the freezing point of 239.124558"

From the info tab on the error:
Code Location: CalculateEquilibrium (file 'C:\Users\Daniel\source\repos\DanWBR\dwsim\DWSIM.Thermodynamics\PropertyPackages\PropertyPackage.vb', line 2229)

Calling Method: CalculateEquilibrium2 (file 'C:\Users\Daniel\source\repos\DanWBR\dwsim\DWSIM.Thermodynamics\PropertyPackages\PropertyPackage.vb', line 2234)

Whether this temperature is in kelvin or celsius it does not make sense with regards to the input parameters...

Screenshot
![Cooling system error](https://user-images.githubusercontent.com/97909782/149820927-66ea2f9c-7e1b-49e3-8bbf-a63493c7c701.PNG)

Desktop:
 - Windows 10 Pro 
 - DWSim Version 7.2.0

Hope you can help me with this issue.
Best Regards,
Paal

**Comment by DanWBR** [comment] 2022-01-23 16:25
@PaalRT please attach the file.

**Comment by PaalRT** [comment] 2022-01-24 08:39
Hi,

See attached.

BR, Pål Ryssdal Tveit

**Comment by DanWBR** [comment] 2022-01-24 12:41
@PaalRT you need to come to GitHub and attach the file here in the issue report, replying to the notification email won't work.

**Comment by PaalRT** [comment] 2022-01-28 07:53
Hi Dan,

sorry for the late response!

Hope this is what you're looking for:
[Cooling System_Error.zip](https://github.com/DanWBR/dwsim/files/7956766/Cooling.System_Error.zip)

BR,
Paal

**Comment by andr1976** [comment] 2022-02-07 13:25
I can confirm the issue, the case solves fine with any UNIFAC or NRTL model

**Comment by DanWBR** [comment] 2022-02-07 14:16
@PaalRT @andr1976  The problem in this case is that CoolProp returns a minimum temperature for this fluid equal to 173.15 K, but then when the saturation pressure is asked at 273.15 K, it says that the temperature is below the minimum value (273.something)...

**Comment by DanWBR** [comment] 2022-02-07 15:05
@andr1976 @PaalRT now it seems that we are left with a CoolProp bug, but I don't think that it is fixed or should be fixed anytime soon...

**Comment by andr1976** [comment] 2022-02-07 21:17
@DanWBR . This is for the water outlet (hot out). It is due to water having a temperature below the freezing point. Setting MSTR-01 / -02 to steam tables PP makes this problem go away - now it is the cold out MSTR-03 which is the problem (see screen dump). I have a sense that it might be some of the HX iteratations which comes out of range for the CoolProp fluids. I tried calling the mixture from python and it works down to the freezing point at 237 K. So DWSIM must call CoolProp with a too low temperature. 

![image](https://user-images.githubusercontent.com/58475535/152873113-68214af9-aaa8-475c-b223-b52a1b6d6ec6.png)

**Comment by DanWBR** [comment] 2022-02-07 21:19
@andr1976 is this with https://github.com/DanWBR/dwsim/commit/0c0dca7dbc336922408ef8b10d01d911cfef5f58?

**Comment by andr1976** [comment] 2022-02-07 21:21
No still using public release 7.3.2, Edit: ha ha,  I  mean 7.3.1 :-)

**Closed as completed** 2022-06-09 12:21 UTC
Labels: external library bug
