### ISSUE TITLE
[Bug] App closes unexpectedly on Ubuntu 21.04

### ISSUE THREAD

**Issue by KeepFloyding** [DanWBR/dwsim6#259] opened 2021-12-15 18:00 UTC
IMPORTANT: This section is for code-related bugs. For usage issues, please go to the [Support Forums](https://sourceforge.net/p/dwsim/discussion/).

**Describe the bug**
When using the pre-compiled debian binary on Ubuntu 21.04, application shuts down after selecting a compressor and moving it in the flow sheet. Error shows the following 

ubuntu-box@ubuntubox-Standard-PC-Q35-ICH9-2009:~/Downloads$ dwsim
Latest Version: 7.1.1
Current Version: 7.1.2
Latest Version: 7.1.1

```
(DWSIM.UI.Desktop:14277): Gtk-WARNING **: 17:46:43.247: Unable to show '': Operation not supported
start creating workbook...
creating workbook done: 0 ms.
start creating worksheet...
init srm takes 96 ms.
creating worksheet done: 105 ms.
Set ScrollBarHorizontalLargeChange to -1
Set ScrollBarVerticalLargeChange to -1
Renderer Dispose Time: 0.155 ms
update viewport bounds done: 11 ms.
Editor Created 94691922005152
Managed Editor Created ScintillaObject
Set ScrollBarHorizontalLargeChange to 1131
Set ScrollBarVerticalLargeChange to 2000
Renderer Dispose Time: 0.017 ms
update viewport bounds done: 1 ms.
Set ScrollBarHorizontalLargeChange to 1121
Set ScrollBarVerticalLargeChange to 2000
Renderer Dispose Time: 0.009 ms
Set ScrollBarHorizontalLargeChange to 634
Set ScrollBarVerticalLargeChange to 2000
Renderer Dispose Time: 0.018 ms
Set ScrollBarHorizontalLargeChange to 562
Set ScrollBarVerticalLargeChange to 2000
Renderer Dispose Time: 0.021 ms
```

**To Reproduce**
1. Dowload debian binary
2. Install on Ubuntu 21.04 with `apt install <path_to_debian_binary>
3. Start a new process project
4. Select a unit operation (in this case a compressor)
5. Move compressor around and application closes

**Expected behavior**
No unexpected closures

**Screenshots**
Crashes after moving this
![image](https://user-images.githubusercontent.com/29730122/146240267-3bbb15c0-cc8b-4ecd-a24b-16860a3f5f9b.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version  21.04

**Additional context**

**Comment by DanWBR** [comment] 2021-12-16 13:26
@KeepFloyding, both normal and wine versions of DWSIM currently run and are supported up to Ubuntu 20.04.2.

**Comment by KeepFloyding** [comment] 2021-12-16 14:12
Ahh ok, thanks for letting me know. Let me use 20.04 then :) 

For future, it might be useful to specify compatible versions (apologies if this information is already somewhere and I missed it). I can add it to the bottom of the README if desired? It might also be good to have it on the website.

**Comment by DanWBR** [comment] 2021-12-16 14:21
@KeepFloyding the problem is a little more complicated than that... DWSIM for Linux is based on GTK2 which is being deprecated everywhere, and upgrading it to GTK3 is not an easy task. I've tried already and failed, unfortunately.

**Comment by KeepFloyding** [comment] 2021-12-17 09:08
@DanWBR would creating a snap help with this? https://snapcraft.io/docs/gtk2-applications

**Comment by andr1976** [comment] 2021-12-17 13:25
@KeepFloyding how do you install dwsim on Ubuntu in the first place, I get tons of dependecy issues, and cannot install mono either (I assume its needed)

**Comment by DanWBR** [comment] 2021-12-17 13:43
@andr1976 I've downloaded Ubuntu 20.04 yesterday:

`
sudo apt install mono-complete mono-vbnc
`

double click on the dwsim debian package and install it.

**Comment by andr1976** [comment] 2021-12-17 14:00
and the mono stuff is included in the standard Ubuntu repos?

**Comment by DanWBR** [comment] 2021-12-17 14:00
> and the mono stuff is included in the standard Ubuntu repos?

@DanWBR yes

**Comment by andr1976** [comment] 2021-12-17 14:02
@DanWBR alright, I am proably hit by some limitations runnning off a virtual machine behind company firewall etc., I will try a clean bare-metal install on an old laptop at home sometime

**Comment by KeepFloyding** [comment] 2021-12-17 15:09
yeah so 20.04 works for me; just download the precompiled debian binary package and do `apt install`; I also ran this in a VM (QEMU)

**Comment by einhander** [comment] 2021-12-17 17:06
It's duplicate of #222. @andr1976 you can use chroot with Ubuntu 20.04 or debian 11 to run dwsim on any linux system. 
@KeepFloyding  I tried to create appimage from precompiled binary but I bumped into mono libraries version mismatched. I think that flatpack or snap package creation will stuck on same issue.  All tutorials said that appimage or flatpack packages can be created during compilation step. 
@DanWBR can dwsim be compiled on linux by mono-develop or similar program?

**Comment by DanWBR** [comment] 2022-06-09 12:21
@einhander the current DWSIM version can't be compiled on Linux, but I'm working on a new GUI-less version of DWSIM that targets .NET 6 which should compile on all supported platforms. I've tested it on Windows only, so far.

**Comment by einhander** [comment] 2022-06-09 12:24
@DanWBR let me know, then prototype will be available. I can test it.

**Comment by DanWBR** [comment] 2022-06-09 12:25
@einhander it is already available for sponsors/patrons: https://github.com/sponsors/DanWBR

**Comment by einhander** [comment] 2022-06-09 12:46
@DanWBR so I need to pay to find bugs in dwsim?;)

**Comment by DanWBR** [comment] 2022-06-09 12:50
@einhander no, you don't. But if you want _early_ access to the .NET 6 prototype, then yes, you do.

**Comment by einhander** [comment] 2022-06-09 12:52
@DanWBR thanks for clarification.

**Comment by DanWBR** [comment] 2022-06-09 12:53
@einhander the .NET 6 version is not public yet. It is just another DWSIM project of many that I have that are not open source yet. I have other private DWSIM repositories that are available for sponsors.

**Comment by DanWBR** [comment] 2022-06-09 12:55
@einhander just to be clear, I am not and I've never asked anyone to pay to find bugs in DWSIM, ok?

**Comment by einhander** [comment] 2022-06-09 13:25
@DanWBR Ok, no problems. Just let me know if you need to test your open source projects on linux. Dwsim is a great software and I want to help it to be even more better.

**Comment by einhander** [comment] 2022-08-18 13:28
@DanWBR please reopen this issue, the problem is not solved in dwsim 8.0.4

**Comment by DanWBR** [comment] 2022-08-18 13:37
@einhander please attach the errors.log file from your Documents/DWSIM Application Data folder

**Comment by einhander** [comment] 2022-08-18 13:45
Here the last line from terminal:
```
--- End of inner exception stack trace ---
  at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore (System.IO.Stream stream, System.Net.Security.SslClientAuthenticationOptions sslOptions, System.Threading.CancellationToken cancellationToken) [0x00117] in <3588d5c507ec48a6b5d13a6d5ae64da2>:0 
  at System.Net.Http.HttpConnectionPool.CreateConnectionAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x0038d] in <3588d5c507ec48a6b5d13a6d5ae64da2>:0 
  at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync (System.Threading.Tasks.ValueTask`1[TResult] creationTask) [0x000e8] in <3588d5c507ec48a6b5d13a6d5ae64da2>:0 
  at System.Net.Http.HttpConnectionPool.SendWithRetryAsync (System.Net.Http.HttpRequestMessage request, System.Boolean doRequestAuth, System.Threading.CancellationToken cancellationToken) [0x00085] in <3588d5c507ec48a6b5d13a6d5ae64da2>:0 
  at System.Net.Http.RedirectHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x00219] in <3588d5c507ec48a6b5d13a6d5ae64da2>:0 
  at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered (System.Threading.Tasks.Task`1[TResult] sendTask, System.Net.Http.HttpRequestMessage request, System.Threading.CancellationTokenSource cts, System.Boolean disposeCts) [0x000e5] in <3588d5c507ec48a6b5d13a6d5ae64da2>:0 
  at System.Net.Http.HttpClient.GetByteArrayAsyncCore (System.Threading.Tasks.Task`1[TResult] getTask) [0x00079] in <3588d5c507ec48a6b5d13a6d5ae64da2>:0 <---
<---

Editor Created 94664834364848
Managed Editor Created ScintillaObject
```
I attached log file, but it doesn't contain last line visible in terminal.
[errors.log](https://github.com/DanWBR/dwsim/files/9374294/errors.log)

Also the root of problem described in #222

**Comment by DanWBR** [comment] 2022-08-18 13:52
@einhander this is not the cause of the crash...

try running DWSIM with

`MONO_LOG_LEVEL=debug dwsim`

and you should see the root exception that led to the crash on the terminal.

**Comment by einhander** [comment] 2022-08-18 13:58
>try running DWSIM with...


Here:
[1.txt](https://github.com/DanWBR/dwsim/files/9374452/1.txt)

**Comment by DanWBR** [comment] 2022-08-18 14:05
Seems to be something related to GTK, as I suspected:

`Mono: DllImport searching in: 'libgtk-x11-2.0.so.0' ('libgtk-x11-2.0.so.0').
Mono: Searching for 'gtk_text_view_set_editable'.
Mono: Probing 'gtk_text_view_set_editable'.
Mono: Found as 'gtk_text_view_set_editable'.
Mono: AOT: FOUND method System.Exception:ToString () [0x7f5dae732150 - 0x7f5dae732184 0x7f5dae9f8d3b]
`

Please try it again with

`MONO_LOG_LEVEL=debug MONO_LOG_MASK=dll dwsim`

**Comment by einhander** [comment] 2022-08-18 14:07
> Please try it again with

Here
[2.txt](https://github.com/DanWBR/dwsim/files/9374539/2.txt)

**Comment by DanWBR** [comment] 2022-08-18 14:10
@einhander thanks. Nothing new on 2.txt. Will try it myself

**Comment by DanWBR** [comment] 2022-08-18 21:37
I've narrowed down the issue to a bug in GTK's SpinButton control, which is not working with XWayland, the compatibility layer for displaying GDK/X11 applications on newer Ubuntu versions. On Ubuntu 16, it uses X11 directly and doesn't crash.

I've replaced all SpinButtons with normal Textboxes, and DWSIM is working OK (so far) on Ubuntu 22.

**Comment by einhander** [comment] 2022-08-19 05:45
> it uses X11 directly and doesn't crash.

I use x11 with awesome wm, so it's not xwayland issue.
>I've replaced all SpinButtons with normal Textboxes, and DWSIM is working OK (so far) on Ubuntu 22.

Great, is test deb available?

**Comment by DanWBR** [comment] 2022-08-22 20:00
@einhander v8.1.0 contains the fix and is now available for download 👍🏻

**Comment by einhander** [comment] 2022-08-23 09:58
@DanWBR thank you! Now I can use dwsim again! This issue can be closed.

**Closed as completed** 2022-09-11 07:54 UTC
Labels: bug
